// <auto-generated />
using System;
using AirBB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirBB.Migrations
{
    [DbContext(typeof(AirBBContext))]
    [Migration("20251023064206_UpdateAfterFixes")]
    partial class UpdateAfterFixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AirBB.Models.Client", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DOB = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@example.com",
                            Name = "John Doe",
                            PhoneNumber = "123-456-7890"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "Chicago"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Boston"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Miami"
                        },
                        new
                        {
                            LocationId = 5,
                            Name = "Los Angeles"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReservationStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidenceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId");

                    b.HasIndex("ResidenceId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.Property<int>("ResidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BathroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BedroomNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GuestNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResidencePicture")
                        .HasColumnType("TEXT");

                    b.HasKey("ResidenceId");

                    b.HasIndex("LocationId");

                    b.ToTable("Residences");

                    b.HasData(
                        new
                        {
                            ResidenceId = 1,
                            BathroomNumber = 1,
                            BedroomNumber = 2,
                            GuestNumber = 4,
                            LocationId = 1,
                            Name = "Chicago Loop Apartment",
                            PricePerNight = 120.00m,
                            ResidencePicture = "chicago-apartment.jpg"
                        },
                        new
                        {
                            ResidenceId = 2,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 2,
                            LocationId = 2,
                            Name = "New York Studio",
                            PricePerNight = 150.00m,
                            ResidencePicture = "ny-studio.jpg"
                        },
                        new
                        {
                            ResidenceId = 3,
                            BathroomNumber = 2,
                            BedroomNumber = 3,
                            GuestNumber = 6,
                            LocationId = 3,
                            Name = "Boston Townhouse",
                            PricePerNight = 200.00m,
                            ResidencePicture = "boston-townhouse.jpg"
                        },
                        new
                        {
                            ResidenceId = 4,
                            BathroomNumber = 3,
                            BedroomNumber = 4,
                            GuestNumber = 8,
                            LocationId = 4,
                            Name = "Miami Beach House",
                            PricePerNight = 300.00m,
                            ResidencePicture = "miami-beach.jpg"
                        },
                        new
                        {
                            ResidenceId = 5,
                            BathroomNumber = 1,
                            BedroomNumber = 1,
                            GuestNumber = 3,
                            LocationId = 5,
                            Name = "LA Modern Apartment",
                            PricePerNight = 180.00m,
                            ResidencePicture = "la-apartment.jpg"
                        });
                });

            modelBuilder.Entity("AirBB.Models.Reservation", b =>
                {
                    b.HasOne("AirBB.Models.Residence", "Residence")
                        .WithMany("Reservations")
                        .HasForeignKey("ResidenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirBB.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Residence");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.HasOne("AirBB.Models.Location", "Location")
                        .WithMany("Residences")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AirBB.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AirBB.Models.Location", b =>
                {
                    b.Navigation("Residences");
                });

            modelBuilder.Entity("AirBB.Models.Residence", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
